[package]
name = "eldiro"
version = "0.1.0"
authors = ["WilliamAB <liams_1998@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
